=== JoyM268/WebTech-CTA/XML/list.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="list">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string" />
                            <xs:element name="description" type="xs:string" />
                            <xs:element name="members" type="xs:string" />
                            <xs:element name="semester" type="xs:string" />
                            <xs:element name="link" type="xs:string" />
                            <xs:element name="email" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JoyM268/WebTech-CTA/xml/list.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="list.xsd">
    <student id="1">
        <title>Project Portal</title>
        <description>A platform to submit your project ideas and check out the projects your peers are doing</description>
        <members>Joy Mascarenhas, Pratham Manabasannanavar</members>
        <semester>4</semester>
        <link>https://joym268.github.io/WebTech-CTA/</link>
        <email>abc@gamil.com</email>
    </student>
    <student id="2">
        <title>Faculty Work Manager</title>
        <description>Web application to track faculty work load.</description>
        <members>Abdul, Bhanu</members>
        <semester>4</semester>
        <link>https://github.com/heyitsELECTRO</link>
        <email>abdul@gmail.com</email>
    </student>
    <student id="3">
        <title>Library Management</title>
        <description>A platform to track the books in library.</description>
        <members>Ramesh, Mukesh, Rohit</members>
        <semester>8</semester>
        <link>https://sdmcetlibrary.com/</link>
        <email>bcd@gmail.com</email>
    </student>
    <student id="4">
        <title>IC Management</title>
        <description>A website to track the IC's in CSE Lab of SDMCET.</description>
        <members>Rahul, Aditya, Abhi, jagdesh</members>
        <semester>4</semester>
        <link>	https://ICtracker.com/</link>
        <email>bef@gmail.com</email>
    </student>
</list>
